firewall:
  #不記錄路徑
  ignoreLogPaths:
  #拒絕訪問連線IP
  denyRemoteIps:
    - 172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}
    - 172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
  #拒絕訪問客戶端IP
  denyClientIps:
  #允許訪問連線IP
  allowRemoteIps:
    - 127\.\d{1,3}\.\d{1,3}\.\d{1,3}
    - 10\.\d{1,3}\.\d{1,3}\.\d{1,3}
    - 192\.168\.\d{1,3}\.\d{1,3}
    - 169\.254\.\d{1,3}\.\d{1,3}
    - 172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}
    - 172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}
    - 172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}

  #允許訪問客戶端IP
  allowClientIps:

  #受保護的路徑
  defendPaths:
    - /env/.+

  #可訪問受保護路徑的連線IP
  accessDefendRemoteIps:
    - 172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}
    - 172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}

  #可訪問受保護路徑的客戶端IP
  accessDefendClientIps:

  #忽略路徑
  ignorePaths:
    - /$
    - /js/
    - /css/
    - /images/
  #忽略檔案類型
  ignoreFileTypes:
    - html
    - js
    - css
  #可跨域IP
  crossDomainIps:
    - 127\.\d{1,3}\.\d{1,3}\.\d{1,3}
    - 10\.\d{1,3}\.\d{1,3}\.\d{1,3}
    - 192\.168\.\d{1,3}\.\d{1,3}
    - 169\.254\.\d{1,3}\.\d{1,3}
    - 172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}
    - 172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}
    - 172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
  #忽略跨域路徑
  ignoreCrossDomainPaths:
    - /$
    - /js/
    - /css/
    - /images/
    - /metrics
  #忽略跨域檔案類型
  ignoreCrossDomainFileTypes:
    - html
    - js
    - css
